<a href="https://colab.research.google.com/github/UjalaPatel/Machine_Learning/blob/master/logistic_play_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
dataset = pd.read_csv("D:\Study\Sem9\ML\Practice\Internal_Practice\winequality-white .csv",";")
dataset.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [ ]:
x = dataset[["citric acid","alcohol","density"]].values
y = dataset["quality"].values

In [ ]:
from sklearn.linear_model import LogisticRegression
logy = LogisticRegression()
logy.fit(x,y)

D:\Software\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
y_pred = logy.predict(x)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y,y_pred))
print(accuracy_score(y,y_pred)*100)
print(logy.score(x,y)*100)

[[   0    0    5   15    0    0    0]
 [   0    0   56  104    3    0    0]
 [   0    0  724  724    9    0    0]
 [   0    0  511 1581  106    0    0]
 [   0    0   99  624  157    0    0]
 [   0    0   18  118   39    0    0]
 [   0    0    0    3    2    0    0]]
50.26541445487954
50.26541445487954
